#!/bin/sh

set -eu

if [ "$(id -u)" != "0" ]; then
    echo "error: must run as root"
    exit 1
fi

srv="${1:-/tmp/srv}"

if [ ! -x "$srv" ]; then
    echo "error: no $srv"
    exit 1
fi

if systemctl is-active --quiet snapd.service snapd.socket; then
    echo "error: snapd (or its socket) still active"
    exit 1
fi

while true; do
    (
        set +e
        for i in `seq 10`; do
            sleep .1
            curl -s --unix-socket /run/snapd.socket 'http:?POKE' > /dev/null && break
            false
        done && chmod -c 0666 /run/snapd.socket
    ) &

    /lib/systemd/systemd-activate -E SNAPD_DEBUG_HTTP=${SNAPD_DEBUG_HTTP:-3} -E SNAPD_DEBUG=${SNAPD_DEBUG:-1} -l /run/snapd.socket "$srv"

    wait
done

