#!/bin/sh

set -eu

if [ "$(id -u)" != "0" ]; then
    echo "error: must run as root"
    exit 1
fi

srv="${1:-/tmp/srv}"

if [ ! -x "$srv" ]; then
    echo "error: no $srv"
    exit 1
fi

if systemctl is-active --quiet snapd.service snapd.socket; then
    echo "error: snapd (or its socket) still active"
    exit 1
fi

if [ "${2:-}" ]; then
    export SNAPPY_FORCE_CPI_URL="$2"
fi

if [ ! -d /usr/lib/snapd ]; then
    mkdir -v /usr/lib/snapd
fi

d=/usr/lib/snapd/snapd
if [ "$srv" != "$d" ]; then
    if [ ! -e "$d" ]; then
        trap exit INT
        trap 'rm -v "$d"' EXIT
    elif [ ! -e "${d}.real" ]; then
        mv -v "$d" "${d}.real"
        trap exit INT
        trap 'mv -v "${d}.real" "$d"; exit' EXIT
    fi
    cp -v "$srv" "$d"
fi

export SNAP_REEXEC=0
export SNAPD_DEBUG="${SNAPD_DEBUG:-1}"
export SNAPD_DEBUG_HTTP="${SNAPD_DEBUG_HTTP:-7}"
export SNAPPY_SQUASHFS_UNPACK_FOR_TESTS="${SNAPPY_SQUASHFS_UNPACK_FOR_TESTS:-0}"
export SNAPPY_TESTING="${SNAPPY_TESTING:-1}"
export SNAP_CONFINE_DEBUG="${SNAP_CONFINE_DEBUG:-1}"

while "$d"; do
    sleep 1 || break
done
