#!/bin/sh

set -eu

if [ "$(id -u)" != "0" ]; then
    echo "error: must run as root"
    exit 1
fi

srv="${1:-/tmp/srv}"

if [ ! -x "$srv" ]; then
    echo "error: no $srv"
    exit 1
fi

if systemctl is-active --quiet snapd.service snapd.socket; then
    echo "error: snapd (or its socket) still active"
    exit 1
fi

exec sudo \
     SNAPD_DEBUG=${SNAPD_DEBUG:-1} \
     SNAPD_DEBUG_HTTP=${SNAPD_DEBUG_HTTP:-3} \
     SNAPPY_SQUASHFS_UNPACK_FOR_TESTS=${SNAPPY_SQUASHFS_UNPACK_FOR_TESTS:-0} \
     SNAPPY_TESTING=${SNAPPY_TESTING:-1} \
     "$srv"
